version: '3.8'

services:
  bot:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: rodcordeiro/bot_pontos:latest
    container_name: pontos_bot
    # restart: always
    ports:
      - '8080:8080'
    env_file:
      - .env
    networks:
      - bots
    volume:
      - ./:/bot

networks:
  bots:
    driver: bridge
