name: Node.js CD

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/bot
            git pull origin main
            yarn
            yarn build
            sudo pm2 restart bot_whats
            
